import "dotenv/config";
import bcrypt from "bcryptjs";
import { PrismaPg } from "@prisma/adapter-pg";
import { Pool } from "pg";
import { PrismaClient } from "../generated/prisma/client";
import { seedTagsAndNav } from "./seed-tags";

const pool = new Pool(
  process.env.PGHOST?.startsWith("/")
    ? {
        host: process.env.PGHOST,
        user: process.env.PGUSER || process.env.USER,
        database: process.env.PGDATABASE || "khan_sofa",
      }
    : { connectionString: process.env.DATABASE_URL! }
);

const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const categories = [
  {
    name: "Sofas",
    slug: "sofas",
    description: "Comfort-first sofas, sectionals, and modular seating",
    imageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1200&q=85",
  },
  {
    name: "Chairs",
    slug: "chairs",
    description: "Dining, accent, and lounge chairs with lasting character",
    imageUrl: "https://images.unsplash.com/photo-1598300056393-4aac492f4344?w=1200&q=85",
  },
  {
    name: "Tables",
    slug: "tables",
    description: "Dining, coffee, side, and occasional tables",
    imageUrl: "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=1200&q=85",
  },
  {
    name: "Beds",
    slug: "beds",
    description: "Upholstered and timber beds designed for restorative spaces",
    imageUrl: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&q=85",
  },
  {
    name: "Storage",
    slug: "storage",
    description: "Sideboards, consoles, cabinets, and shelving",
    imageUrl: "https://images.unsplash.com/photo-1558997519-83ea9252edf8?w=1200&q=85",
  },
  {
    name: "Outdoor",
    slug: "outdoor",
    description: "Relaxed furniture made for open-air living",
    imageUrl: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1200&q=85",
  },
];

const products = [
  {
    handle: "sofia-three-seat-sofa",
    sku: "KS-SOF-SOFIA-3S",
    categorySlug: "sofas",
    name: "Sofia Three-Seat Sofa",
    shortDescription: "Deep, relaxed seating tailored in family-friendly performance linen",
    brand: "Khan Studio",
    price: 1899,
    stock: 8,
    rating: 4.9,
    reviewCount: 38,
    primaryImageUrl: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1200&q=85",
    secondaryImageUrl: "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=1200&q=85",
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1200&q=85",
      "https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=1200&q=85",
    ],
    description: "Sofia balances generous proportions with a quiet, architectural profile. High-resilience foam and feather-blend cushions create a soft seat that recovers beautifully, while removable covers make everyday care simple.",
    status: "In Stock",
    isNewArrival: true,
    isBestSeller: true,
    colors: ["Oatmeal", "Sage", "Charcoal"],
    configurations: ["3 Seater", "2.5 Seater"],
    furnitureType: "Sofa",
    material: "Performance linen, kiln-dried hardwood",
    upholsteryMaterial: "Performance Linen",
    frameMaterial: "Kiln-dried Hardwood",
    cushionFilling: "Foam & Feather Blend",
    finish: "Upholstered",
    room: "Living Room",
    dimensions: "W 228 × D 98 × H 82 cm",
    widthCm: 228,
    depthCm: 98,
    heightCm: 82,
    seatHeightCm: 44,
    seatingCapacity: 3,
    weightKg: 78,
    maxLoadKg: 350,
    assemblyRequired: true,
    warrantyMonths: 36,
    careInstructions: "Vacuum with a soft brush weekly. Blot spills immediately with a clean, dry cloth.",
    productTags: ["Living Room", "Sofas & Sectionals", "Performance Fabric", "Contemporary", "Best Sellers"],
  },
  {
    handle: "noor-modular-corner-sofa",
    sku: "KS-SEC-NOOR-CORNER",
    categorySlug: "sofas",
    name: "Noor Modular Corner Sofa",
    shortDescription: "A low-slung modular sofa made for expansive, easy living",
    brand: "Khan Studio",
    price: 2799,
    stock: 5,
    rating: 4.8,
    reviewCount: 24,
    primaryImageUrl: "https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=1200&q=85",
    secondaryImageUrl: "https://images.unsplash.com/photo-1550254478-ead40cc54513?w=1200&q=85",
    images: [
      "https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=1200&q=85",
      "https://images.unsplash.com/photo-1550254478-ead40cc54513?w=1200&q=85",
    ],
    description: "Noor's adaptable modules create a generous corner setting without visual weight. The tactile woven upholstery is paired with a reinforced hardwood frame and supportive pocket-spring seat construction.",
    status: "In Stock",
    isNewArrival: true,
    isBestSeller: false,
    colors: ["Warm Sand", "Moss", "Stone"],
    configurations: ["Left Chaise", "Right Chaise", "Four Piece Modular"],
    furnitureType: "Sectional Sofa",
    material: "Textured weave, hardwood, pocket springs",
    upholsteryMaterial: "Performance Linen",
    frameMaterial: "Kiln-dried Hardwood",
    cushionFilling: "Pocket Spring & Foam",
    finish: "Upholstered",
    room: "Living Room",
    dimensions: "W 294 × D 184 × H 76 cm",
    widthCm: 294,
    depthCm: 184,
    heightCm: 76,
    seatHeightCm: 42,
    seatingCapacity: 5,
    weightKg: 128,
    maxLoadKg: 550,
    assemblyRequired: true,
    warrantyMonths: 36,
    careInstructions: "Rotate cushions monthly. Professional upholstery cleaning is recommended.",
    productTags: ["Living Room", "Sofas & Sectionals", "Performance Fabric", "Organic Modern", "New Arrivals", "Statement Pieces"],
  },
  {
    handle: "atlas-boucle-lounge-chair",
    sku: "KS-CHR-ATLAS-01",
    categorySlug: "chairs",
    name: "Atlas Bouclé Lounge Chair",
    shortDescription: "Sculptural curves and enveloping comfort in tactile bouclé",
    brand: "North House",
    price: 649,
    stock: 14,
    rating: 4.7,
    reviewCount: 31,
    primaryImageUrl: "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=1200&q=85",
    secondaryImageUrl: "https://images.unsplash.com/photo-1598300056393-4aac492f4344?w=1200&q=85",
    images: [
      "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=1200&q=85",
      "https://images.unsplash.com/photo-1598300056393-4aac492f4344?w=1200&q=85",
    ],
    description: "Atlas is a compact statement chair with a softly curved back and supportive seat. Its durable bouclé upholstery brings warmth and texture to reading corners, bedrooms, and conversation spaces.",
    status: "In Stock",
    isNewArrival: false,
    isBestSeller: true,
    colors: ["Ivory", "Rust", "Forest"],
    configurations: ["Standard"],
    furnitureType: "Armchair",
    material: "Bouclé, molded foam, solid ash",
    upholsteryMaterial: "Bouclé",
    frameMaterial: "Solid Ash",
    cushionFilling: "High-resilience Foam",
    finish: "Upholstered",
    room: "Living Room",
    dimensions: "W 78 × D 80 × H 74 cm",
    widthCm: 78,
    depthCm: 80,
    heightCm: 74,
    seatHeightCm: 43,
    seatingCapacity: 1,
    weightKg: 22,
    maxLoadKg: 140,
    assemblyRequired: false,
    warrantyMonths: 24,
    careInstructions: "Use a fabric brush for surface dust. Do not saturate the upholstery.",
    productTags: ["Living Room", "Bedroom", "Accent Chairs", "Bouclé", "Organic Modern", "Best Sellers", "Small Space"],
  },
  {
    handle: "sienna-oak-dining-table",
    sku: "KS-TBL-SIENNA-200",
    categorySlug: "tables",
    name: "Sienna Oak Dining Table",
    shortDescription: "A solid oak table with softened edges and a grounded silhouette",
    brand: "Form & Grain",
    price: 1499,
    stock: 7,
    rating: 4.9,
    reviewCount: 19,
    primaryImageUrl: "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=1200&q=85",
    secondaryImageUrl: "https://images.unsplash.com/photo-1604578762246-41134e37f9cc?w=1200&q=85",
    images: [
      "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=1200&q=85",
      "https://images.unsplash.com/photo-1604578762246-41134e37f9cc?w=1200&q=85",
    ],
    description: "Crafted from solid European oak, Sienna celebrates natural grain and subtle variation. Rounded corners and pedestal-style legs make it inviting, practical, and easy to gather around.",
    status: "In Stock",
    isNewArrival: true,
    isBestSeller: true,
    colors: ["Natural Oak", "Smoked Oak"],
    configurations: ["Six Seater", "Eight Seater"],
    furnitureType: "Dining Table",
    material: "Solid European oak",
    upholsteryMaterial: "None",
    frameMaterial: "Solid Oak",
    cushionFilling: "None",
    finish: "Oiled",
    room: "Dining Room",
    dimensions: "W 200 × D 100 × H 76 cm",
    widthCm: 200,
    depthCm: 100,
    heightCm: 76,
    seatingCapacity: 8,
    weightKg: 72,
    maxLoadKg: 120,
    assemblyRequired: true,
    warrantyMonths: 60,
    careInstructions: "Wipe with a slightly damp cloth and dry immediately. Use coasters and trivets.",
    productTags: ["Dining Room", "Dining Tables", "Solid Wood", "Organic Modern", "Best Sellers"],
  },
  {
    handle: "mira-cane-dining-chair",
    sku: "KS-CHR-MIRA-CANE",
    categorySlug: "chairs",
    name: "Mira Cane Dining Chair",
    shortDescription: "A warm timber dining chair with a hand-woven cane back",
    brand: "Form & Grain",
    price: 329,
    stock: 24,
    rating: 4.6,
    reviewCount: 17,
    primaryImageUrl: "https://images.unsplash.com/photo-1503602642458-232111445657?w=1200&q=85",
    secondaryImageUrl: "https://images.unsplash.com/photo-1592078615290-033ee584e267?w=1200&q=85",
    images: [
      "https://images.unsplash.com/photo-1503602642458-232111445657?w=1200&q=85",
      "https://images.unsplash.com/photo-1592078615290-033ee584e267?w=1200&q=85",
    ],
    description: "Mira pairs a solid ash frame with an airy woven-cane back. A gently curved seat and supportive proportions make it comfortable enough for long dinners and everyday work.",
    status: "In Stock",
    isNewArrival: false,
    isBestSeller: false,
    colors: ["Natural", "Walnut", "Black"],
    configurations: ["Single Chair", "Set of Two", "Set of Four"],
    furnitureType: "Dining Chair",
    material: "Solid ash, natural cane",
    upholsteryMaterial: "None",
    frameMaterial: "Rattan / Cane",
    cushionFilling: "None",
    finish: "Natural",
    room: "Dining Room",
    dimensions: "W 49 × D 54 × H 82 cm",
    widthCm: 49,
    depthCm: 54,
    heightCm: 82,
    seatHeightCm: 46,
    seatingCapacity: 1,
    weightKg: 7.5,
    maxLoadKg: 120,
    assemblyRequired: false,
    warrantyMonths: 24,
    careInstructions: "Dust regularly. Keep cane away from direct heat and prolonged moisture.",
    productTags: ["Dining Room", "Dining Chairs", "Solid Wood", "Rattan", "Mid-century"],
  },
  {
    handle: "zeenat-upholstered-bed",
    sku: "KS-BED-ZEENAT-QN",
    categorySlug: "beds",
    name: "Zeenat Upholstered Bed",
    shortDescription: "A serene upholstered bed with a gently winged headboard",
    brand: "Quiet Form",
    price: 1699,
    stock: 6,
    rating: 4.8,
    reviewCount: 22,
    primaryImageUrl: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&q=85",
    secondaryImageUrl: "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200&q=85",
    images: [
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=1200&q=85",
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1200&q=85",
    ],
    description: "Zeenat creates a calm focal point with softly tailored upholstery and a sheltering headboard. A solid slat system provides quiet, even mattress support without a box spring.",
    status: "In Stock",
    isNewArrival: true,
    isBestSeller: false,
    colors: ["Flax", "Dove", "Olive"],
    configurations: ["Queen", "King"],
    furnitureType: "Bed",
    material: "Linen blend, engineered hardwood",
    upholsteryMaterial: "Linen Blend",
    frameMaterial: "Engineered Hardwood",
    cushionFilling: "High-resilience Foam",
    finish: "Upholstered",
    room: "Bedroom",
    dimensions: "W 177 × D 224 × H 118 cm (Queen)",
    widthCm: 177,
    depthCm: 224,
    heightCm: 118,
    weightKg: 84,
    maxLoadKg: 350,
    assemblyRequired: true,
    warrantyMonths: 36,
    careInstructions: "Vacuum upholstery gently. Tighten frame hardware after the first month of use.",
    productTags: ["Bedroom", "Beds", "Performance Fabric", "Minimal", "New Arrivals"],
  },
  {
    handle: "oakline-bedside-table",
    sku: "KS-STO-OAKLINE-48",
    categorySlug: "storage",
    name: "Oakline Bedside Table",
    shortDescription: "Compact bedside storage with a seamless drawer and open shelf",
    brand: "Form & Grain",
    price: 389,
    stock: 18,
    rating: 4.5,
    reviewCount: 14,
    primaryImageUrl: "https://images.unsplash.com/photo-1551298370-9d3d53740c72?w=1200&q=85",
    secondaryImageUrl: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=85",
    images: [
      "https://images.unsplash.com/photo-1551298370-9d3d53740c72?w=1200&q=85",
      "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=1200&q=85",
    ],
    description: "Oakline keeps evening essentials close without clutter. The soft-close drawer, open lower shelf, and chamfered solid-oak edges bring considered utility to compact bedrooms.",
    status: "In Stock",
    isNewArrival: false,
    isBestSeller: true,
    colors: ["Natural Oak", "Smoked Oak"],
    configurations: ["Left Opening", "Right Opening"],
    furnitureType: "Bedside Table",
    material: "Solid oak, oak veneer",
    upholsteryMaterial: "None",
    frameMaterial: "Solid Oak",
    cushionFilling: "None",
    finish: "Natural",
    room: "Bedroom",
    dimensions: "W 48 × D 40 × H 54 cm",
    widthCm: 48,
    depthCm: 40,
    heightCm: 54,
    weightKg: 18,
    maxLoadKg: 35,
    assemblyRequired: false,
    warrantyMonths: 36,
    careInstructions: "Dust with a soft cloth. Clean spills promptly and avoid abrasive cleaners.",
    productTags: ["Bedroom", "Storage Furniture", "Solid Wood", "Minimal", "Best Sellers", "Small Space"],
  },
  {
    handle: "vale-travertine-coffee-table",
    sku: "KS-TBL-VALE-120",
    categorySlug: "tables",
    name: "Vale Travertine Coffee Table",
    shortDescription: "A monolithic coffee table shaped by the warmth of natural stone",
    brand: "North House",
    price: 899,
    stock: 9,
    rating: 4.7,
    reviewCount: 12,
    primaryImageUrl: "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=1200&q=85",
    secondaryImageUrl: "https://images.unsplash.com/photo-1538688423619-a81d3f23454b?w=1200&q=85",
    images: [
      "https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=1200&q=85",
      "https://images.unsplash.com/photo-1538688423619-a81d3f23454b?w=1200&q=85",
    ],
    description: "Each Vale table is finished in hand-selected travertine veneer, so tone and veining are naturally unique. Its rounded rectangular form feels substantial while keeping circulation easy.",
    status: "In Stock",
    isNewArrival: true,
    isBestSeller: false,
    colors: ["Natural Travertine"],
    configurations: ["120 cm", "90 cm"],
    furnitureType: "Coffee Table",
    material: "Travertine stone veneer",
    upholsteryMaterial: "None",
    frameMaterial: "Stone",
    cushionFilling: "None",
    finish: "Polished Stone",
    room: "Living Room",
    dimensions: "W 120 × D 65 × H 36 cm",
    widthCm: 120,
    depthCm: 65,
    heightCm: 36,
    weightKg: 48,
    maxLoadKg: 80,
    assemblyRequired: false,
    warrantyMonths: 24,
    careInstructions: "Use coasters. Wipe spills immediately and avoid acidic or abrasive cleaning products.",
    productTags: ["Living Room", "Coffee & Side Tables", "Marble", "Contemporary", "New Arrivals", "Statement Pieces"],
  },
  {
    handle: "reed-media-console",
    sku: "KS-STO-REED-180",
    categorySlug: "storage",
    name: "Reed Media Console",
    shortDescription: "Fluted timber storage that keeps media equipment beautifully concealed",
    brand: "Khan Studio",
    price: 1199,
    stock: 7,
    rating: 4.8,
    reviewCount: 26,
    primaryImageUrl: "https://images.unsplash.com/photo-1558997519-83ea9252edf8?w=1200&q=85",
    secondaryImageUrl: "https://images.unsplash.com/photo-1618220179428-22790b461013?w=1200&q=85",
    images: [
      "https://images.unsplash.com/photo-1558997519-83ea9252edf8?w=1200&q=85",
      "https://images.unsplash.com/photo-1618220179428-22790b461013?w=1200&q=85",
    ],
    description: "Reed combines sculptural fluted doors with practical cable management, adjustable shelves, and soft-close hinges. The ventilated back keeps equipment tidy and cool.",
    status: "In Stock",
    isNewArrival: false,
    isBestSeller: true,
    colors: ["Walnut", "Natural Oak", "Black Oak"],
    configurations: ["180 cm", "220 cm"],
    furnitureType: "Media Console",
    material: "Oak veneer, solid timber base",
    upholsteryMaterial: "None",
    frameMaterial: "Solid Oak",
    cushionFilling: "None",
    finish: "Walnut Stain",
    room: "Living Room",
    dimensions: "W 180 × D 45 × H 58 cm",
    widthCm: 180,
    depthCm: 45,
    heightCm: 58,
    weightKg: 56,
    maxLoadKg: 100,
    assemblyRequired: true,
    warrantyMonths: 36,
    careInstructions: "Dust regularly with a dry microfiber cloth. Keep ventilation openings clear.",
    productTags: ["Living Room", "Storage Furniture", "Solid Wood", "Contemporary", "Best Sellers"],
  },
  {
    handle: "sol-outdoor-lounge-set",
    sku: "KS-OUT-SOL-4PC",
    categorySlug: "outdoor",
    name: "Sol Outdoor Lounge Set",
    shortDescription: "Weather-ready lounge seating for slow afternoons outside",
    brand: "Open Air",
    price: 2199,
    stock: 4,
    rating: 4.6,
    reviewCount: 11,
    primaryImageUrl: "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1200&q=85",
    secondaryImageUrl: "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=1200&q=85",
    images: [
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1200&q=85",
      "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?w=1200&q=85",
    ],
    description: "Sol includes a two-seat lounge, two generous armchairs, and a low coffee table. Powder-coated aluminum frames and quick-dry cushions are designed for covered outdoor spaces.",
    status: "In Stock",
    isNewArrival: true,
    isBestSeller: false,
    colors: ["Sand", "Graphite"],
    configurations: ["Four Piece Set"],
    furnitureType: "Outdoor Furniture",
    material: "Powder-coated aluminum, solution-dyed fabric",
    upholsteryMaterial: "Solution-dyed Outdoor Fabric",
    frameMaterial: "Aluminum",
    cushionFilling: "Quick-dry Outdoor Foam",
    finish: "Powder-coated",
    room: "Outdoor",
    dimensions: "Sofa W 164 × D 82 × H 74 cm",
    widthCm: 164,
    depthCm: 82,
    heightCm: 74,
    seatHeightCm: 42,
    seatingCapacity: 4,
    weightKg: 64,
    maxLoadKg: 500,
    assemblyRequired: true,
    warrantyMonths: 24,
    careInstructions: "Cover when not in use. Store cushions indoors during severe weather.",
    productTags: ["Outdoor", "Outdoor Furniture", "Performance Fabric", "Contemporary", "New Arrivals"],
  },
];

const reviews = [
  {
    productIndex: 0,
    authorName: "Ayesha M.",
    rating: 5,
    comment: "The Sofia sofa is even more comfortable than it looks. The fabric has already handled family movie nights beautifully.",
  },
  {
    productIndex: 2,
    authorName: "Daniel R.",
    rating: 5,
    comment: "This chair completely changed our reading corner. It feels solid, supportive, and the bouclé texture is lovely in person.",
  },
  {
    productIndex: 3,
    authorName: "Mariam K.",
    rating: 5,
    comment: "The oak grain is beautiful and the rounded corners make the table feel relaxed rather than formal. Delivery was well coordinated.",
  },
  {
    productIndex: 5,
    authorName: "Hassan A.",
    rating: 5,
    comment: "Excellent build quality and a very calm, refined look. Assembly instructions were clear and the frame feels completely stable.",
  },
];

async function main() {
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.review.deleteMany();
  await prisma.product.deleteMany();
  await prisma.category.deleteMany();
  await prisma.coupon.deleteMany();
  await prisma.user.deleteMany();

  const tagByName = await seedTagsAndNav(prisma);

  const adminPassword = await bcrypt.hash("admin123", 10);
  await prisma.user.create({
    data: {
      name: "Admin",
      email: "admin@khansofa.com",
      password: adminPassword,
      role: "ADMIN",
    },
  });

  const categoryMap = new Map<string, number>();
  for (const category of categories) {
    const created = await prisma.category.create({ data: category });
    categoryMap.set(category.slug, created.id);
  }

  const createdProducts = [];
  for (const product of products) {
    const { categorySlug, productTags, ...data } = product;
    const tagIds = productTags
      .map((name) => tagByName.get(name.toLowerCase())?.id)
      .filter((id): id is number => id !== undefined);

    const created = await prisma.product.create({
      data: {
        ...data,
        categoryId: categoryMap.get(categorySlug)!,
        tags: { connect: tagIds.map((id) => ({ id })) },
      },
    });
    createdProducts.push(created);
  }

  for (const review of reviews) {
    await prisma.review.create({
      data: {
        productId: createdProducts[review.productIndex].id,
        authorName: review.authorName,
        rating: review.rating,
        comment: review.comment,
      },
    });
  }

  await prisma.coupon.create({
    data: {
      code: "WELCOME10",
      discountType: "percent",
      discountValue: 10,
      isActive: true,
    },
  });

  console.log("Khan Sofa database seeded successfully");
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await pool.end();
  });
